name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install flake8 black isort mypy types-flask

    - name: Check formatting with Black
      working-directory: ./app
      run: black --check src tests

    - name: Check import sorting with isort
      working-directory: ./app
      run: isort --check-only src tests

    - name: Lint with flake8
      working-directory: ./app
      run: flake8 src tests

    - name: Type check with mypy
      working-directory: ./app
      run: mypy src tests 