name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      firestore:
        image: mtlynch/firestore-emulator
        ports:
          - 8081:8081
        env:
          FIRESTORE_PROJECT_ID: test-project

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run tests
      working-directory: ./app
      env:
        FIRESTORE_EMULATOR_HOST: localhost:8081
        GOOGLE_CLOUD_PROJECT: test-project
      run: |
        pytest --cov=src --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./app/coverage.xml
        fail_ci_if_error: true 